In [1]:
#### SVM ( SUPPORT VECTOR MACHINE ALGO )

## import the libraries

import os
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot

In [3]:
## Import data set from the existing library of sklearn

from sklearn import datasets

cancer = datasets.load_breast_cancer()

In [12]:
## Print the Features and lables

print(f"Features: {cancer.feature_names}")
print(f"Lables: {cancer.target_names}")

Features: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Lables: ['malignant' 'benign']


In [13]:
# Now train and split the model

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(cancer.data,cancer.target,test_size=0.3, random_state=109)

In [14]:
# import SVM model

from sklearn import svm
svm_model = svm.SVC(kernel='linear')
svm_model.fit(x_train,y_train)
y_pred = svm_model.predict(x_test)

In [16]:
# now check the accuracy

from sklearn.metrics import accuracy_score
print (f"Accuracy Score is : {accuracy_score(y_test,y_pred)}")

Accuracy Score is : 0.9649122807017544


In [17]:
# now print the precission and recall

from sklearn import metrics

print ("Precession:", metrics.precision_score(y_test,y_pred))
print ("Recall Score", metrics.recall_score(y_test,y_pred))

Precession: 0.9811320754716981
Recall Score 0.9629629629629629


In [19]:
# check the confusion metrics

from sklearn.metrics import confusion_matrix
Confusion_Matrix = confusion_matrix(y_test,y_pred)
Confusion_Matrix

array([[ 61,   2],
       [  4, 104]], dtype=int64)

In [21]:
# Now display the classification report 

from sklearn.metrics import classification_report
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95        63
           1       0.98      0.96      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171



In [48]:
# Now check for IRIS DATA 

iris_data = datasets.load_iris
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"



In [49]:
# specify the col names

col_names = ['sepal-length','sepal-width','petal-length','petal-width','class']
irisdata=pd.read_csv(url,names=col_names)

In [50]:
irisdata.head()

sepal-length  sepal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [51]:
# check the unique class
irisdata['class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [52]:
# Create Lable and Features

x = irisdata.drop('class',axis=1)
y= irisdata['class']

In [53]:
# Now again train the model with above feature and lables

X_train,X_test,Y_train,Y_test = train_test_split(x,y,test_size=0.20,random_state=42)

In [54]:
# now load the model to the train and testing data

from sklearn.svm import SVC
svc_model = SVC(kernel='poly',degree=1)
svc_model.fit(X_train,Y_train)
Y_pred = svc_model.predict(X_test)

In [56]:
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [57]:
# Support vector classifier

svclassifier = SVC(kernel='rbf',gamma=0.1)
svclassifier.fit(X_train,Y_train)


SVC(gamma=0.1)

In [58]:
Y_pred = svclassifier.predict(X_test)

In [59]:
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [ ]:
'''
Completed in this sheet 

1. SVM Model
2. SVC with Degree =1 and kernel = 'Poly'
3. SVC with Kernel = 'rbf' and gamma= 0.1
'''