In [1]:
#svm

import numpy as np
import pandas as pd 

from sklearn import datasets

cancer=datasets.load_breast_cancer()

In [2]:
print("Features:",cancer.feature_names)
print("Lables:",cancer.target_names)

Features: ['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
Lables: ['malignant' 'benign']


In [3]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(cancer.data,cancer.target,test_size=0.3,random_state=109)

In [4]:
from sklearn import svm
clf=svm.SVC(kernel='linear')
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

In [5]:
from sklearn import metrics 
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))

Accuracy: 0.9649122807017544


In [6]:
print("Precision:",metrics.precision_score(y_test,y_pred))
print("Recall:",metrics.recall_score(y_test,y_pred))

Precision: 0.9811320754716981
Recall: 0.9629629629629629


In [7]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm 

array([[ 61,   2],
       [  4, 104]], dtype=int64)

In [8]:
from sklearn.metrics import classification_report 
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95        63
           1       0.98      0.96      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.97      0.96       171
weighted avg       0.97      0.96      0.97       171



In [9]:
irisdata=datasets.load_iris

In [10]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

colnames=['sepal-length','sepal-width','petal-length','petal-width','Class']

irisdata=pd.read_csv(url,names=colnames)

In [11]:
irisdata

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [12]:
irisdata['Class'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [13]:
X=irisdata.drop('Class',axis=1)
y=irisdata['Class']

In [28]:
from sklearn.model_selection import train_test_split 
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [29]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='poly',degree=1)
svclassifier.fit(X_train,y_train)

SVC(degree=1, kernel='poly')

In [30]:
y_pred=svclassifier.predict(X_test)

In [31]:
from sklearn.metrics import classification_report,confusion_matrix 
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [32]:
svclassifier=SVC(kernel='rbf',gamma=0.1)
svclassifier.fit(X_train,y_train)

SVC(gamma=0.1)

In [33]:
y_pred=svclassifier.predict(X_test)

In [34]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

